CREATE TABLE reservas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre TEXT NOT NULL,
  curso TEXT NOT NULL,
  fecha DATE NOT NULL,
  hora_inicio TIME NOT NULL,
  hora_fin TIME NOT NULL,
  motivo TEXT NOT NULL,
  estado TEXT DEFAULT 'pendiente' CHECK (estado IN ('pendiente', 'aprobada', 'rechazada')),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE reservas ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Permitir lectura pública" ON reservas FOR SELECT USING (true);
CREATE POLICY "Permitir inserción pública" ON reservas FOR INSERT WITH CHECK (true);
CREATE POLICY "Permitir actualización pública" ON reservas FOR UPDATE USING (true);
CREATE POLICY "Permitir eliminación pública" ON reservas FOR DELETE USING (true);